### ISSUE TITLE
How to remove trimming empty spaces around image?

### ISSUE THREAD

**Issue by PAHANIUS** [UncorkedStudios/export-to-ios#2]
I have an image with empty transparent spaces on sides. This script cut my image sides until picture. How to remove it?
Thanks.

**Comment by gastonfig** [comment]
@PAHANIUS You can create a rectangle (doesn't matter the color) the size of your image plus the desired space around it. Make that new layer transparent (change it's fill to 0%) and then move it inside a layergroup together with the layer that contains your image. You then just run the action with that layergroup selected and that should export the image with the desired transparent space around it.

Hope this helps.
